In [19]:
import pandas as pd

In [20]:
df=pd.read_csv('messy_employee_data.csv')
df.head()

,EmployeeID,FirstName,LastName,Age,Gender,City,Department,Salary,JoinDate,Email,PerformanceRating
0,12,William,Moore,45.0,F,Chicago,Sales,60000.5,2022-07-19,william.moore@example.com,1
1,130,David,Williams,29.0,Male,Miami,Sales,52000.0,2021-05-01,david.williams@example.com,5 stars
2,141,Sarah,Johnson,40.0,Male,Miami,Marketing,88000.0,15-03-2022,sarah.johnson@example.com,10
3,157,Anna,Jones,35.0,M,Miami,Finance,60000.5,01/06/2020,anna.jones@example.com,3.5
4,103,Emily,Wilson,-5.0,Female,chicago,Finance,73000.0,15-03-2022,emily.wilson@example.com,4

In [21]:
df.shape
df.info()
df.describe()
df.dtypes

<class 'pandas.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         209 non-null    int64
 1   FirstName          209 non-null    str
 2   LastName           209 non-null    str
 3   Age                193 non-null    float64
 4   Gender             178 non-null    str
 5   City               177 non-null    str
 6   Department         183 non-null    str
 7   Salary             168 non-null    float64
 8   JoinDate           180 non-null    str
 9   Email              201 non-null    str
 10  PerformanceRating  187 non-null    str
dtypes: float64(2), int64(1), str(8)
memory usage: 18.1 KB

EmployeeID             int64
FirstName                str
LastName                 str
Age                  float64
Gender                   str
City                     str
Department               str
Salary               float64
JoinDate                 str
Email                    str
PerformanceRating        str
dtype: object

In [22]:
df.isnull().sum()

EmployeeID            0
FirstName             0
LastName              0
Age                  16
Gender               31
City                 32
Department           26
Salary               41
JoinDate             29
Email                 8
PerformanceRating    22
dtype: int64

In [23]:
df[df.duplicated()]
df.drop_duplicates(inplace=True)

In [27]:
df['FirstName'] = df['FirstName'].str.title()
df['LastName'] = df['LastName'].str.title()
df['City'] = df['City'].str.title()
df['Department'] = df['Department'].str.title()
df

,EmployeeID,FirstName,LastName,Age,Gender,City,Department,Salary,JoinDate,Email,PerformanceRating
0,12,William,Moore,45.0,F,Chicago,Sales,60000.5,2022-07-19,william.moore@example.com,1
1,130,David,Williams,29.0,Male,Miami,Sales,52000.0,2021-05-01,david.williams@example.com,5 stars
2,141,Sarah,Johnson,40.0,Male,Miami,Marketing,88000.0,15-03-2022,sarah.johnson@example.com,10
3,157,Anna,Jones,35.0,M,Miami,Finance,60000.5,01/06/2020,anna.jones@example.com,3.5
4,103,Emily,Wilson,-5.0,Female,Chicago,Finance,73000.0,15-03-2022,emily.wilson@example.com,4
...,...,...,...,...,...,...,...,...,...,...,...
204,152,Mike,Moore,50.0,Male,Boston,Marketing,NaN,01/06/2020,mike.moore@example.com,NaN
205,68,Lisa,Moore,28.0,M,Boston,Sales,88000.0,01/06/2020,lisa.moore@example.com,5
206,26,Sarah,Johnson,50.0,M,Miami,Sales,60000.5,2021-05-01,sarah.johnson@example.com,4
207,197,Mary,Williams,40.0,F,Miami,Marketing,73000.0,2019/11/23,mary.williams@example.com,3.5
208,176,Mary,Williams,28.0,Female,Houston,Sales,52000.0,2021-05-01,mary.williams@example.com,3

In [34]:

df['Gender'] = df['Gender'].str.lower()
df.replace({'Gender': {'f': 'female', 'm': 'male'}}, inplace=True)
df['Gender'].unique()

<StringArray>
['female', 'male', nan]
Length: 3, dtype: str

In [37]:

df.replace({'City': {'L.A.': 'Los Angeles'}}, inplace=True)
df['City'].unique()

<StringArray>
[    'Chicago',       'Miami',      'Miami ',    'Chicago ',     'Houston',
           nan, 'Los Angeles',    'New York',      'Boston']
Length: 9, dtype: str

In [44]:
df['Salary']=pd.to_numeric(df['Salary'], errors='coerce')
df['JoinDate'] = pd.to_numeric(df['JoinDate'], errors='coerce')