In [111]:
import pandas as pd
df=pd.DataFrame()

In [112]:
df['Name']=['Hari','Priya']
df['Age']=['22','23']
df

    Name Age
0   Hari  22
1  Priya  23

In [113]:
new_row=pd.DataFrame([['Kavya','25']],columns=['Name','Age'])
df=pd.concat([df,new_row])
df

    Name Age
0   Hari  22
1  Priya  23
0  Kavya  25

In [114]:
print(df.shape)
print(df.info())
print(df.describe())

(3, 2)
<class 'pandas.DataFrame'>
Index: 3 entries, 0 to 0
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      str
dtypes: str(2)
memory usage: 72.0 bytes
None
        Name Age
count      3   3
unique     3   3
top     Hari  22
freq       1   1

In [115]:
df1=df.drop('Age',axis=1)
df1

    Name
0   Hari
1  Priya
0  Kavya

In [116]:
df.iloc[0]

Name    Hari
Age       22
Name: 0, dtype: str

In [117]:
df['Age'] = ['22', '23', '25']

In [118]:
df

    Name Age
0   Hari  22
1  Priya  23
0  Kavya  25

In [119]:
df['Age'] = pd.to_numeric(df['Age'])
print(df[df['Age']>22])

    Name  Age
1  Priya   23
0  Kavya   25

In [120]:
print(df.sort_values(by='Age'))

    Name  Age
0   Hari   22
1  Priya   23
0  Kavya   25